

services:
  app:
    container_name: app_sns
    build: ./docker/php
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "5173:5173"
  nginx:
    image: nginx
    container_name: nginx_sns
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: db_sns
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atlas_sns
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_HOST=db_sns
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
